// bgg-catalog.js — generated by scripts/generate-catalog.js
// Run  node scripts/generate-catalog.js  on your local machine to populate this.
// Requires:  npm install jsdom  in the scripts/ directory first.
window.BGG_CATALOG = [];
